apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: acr-secret
spec:
  encryptedData:
    .dockerconfigjson: AgC5ZOOn3HnftPapeZYRrIYqWmhmZ2hMhBN9Zfvno4nEEZGCaQQ1t0GN9KygMlWuN5tHNOfBozrt4H8VZLswUZII9h+1EjQ88in/bZvrnLWLORVDQlsNHOL4h7CdjX0/jUTQAqCHx6uFbm57SWr2kl8+71XSPZ05F/cIq9Hx5R4OxPKyVWeeLCRQ2J1QHO4YkwMjbwDhDYNdUdKo6EYMdgfbX3zcaQ4lpjGYS8BQpziOtf8HuB4YrzS/gm5Js4VZAFEWF86lqvX7D8gEkOaKIk3EKJcwomqYmQal7QsLKnZHf/ysyoAzZAQvzk9PXkwX1s34+DGW7dX2amXI0FHeQZwRZZI8gH4qCIeBiA4nVNmwGcXNxVSxG72D0T6+irmPFH1Ff3zzJpu8BQD+HqWTewYdjGptN+pogzF5S+hYHVfe3Mf+sKgU35kKhRuzdDwHiklNOjh3fuJGnAbTqqiJYoPTDYWXkH7r/m5Hl75DkW6SNOfx9V3y2h+BEFcWQCae6t8Ru4e1wcaWsF7jyoV1FcaiKCEcLLmFo+dgQXJaHYQPBHu4+/685/wz10+Pad4wD7AZEEG+JmaLmMNJBzRDJYfHXiRF4YDAK5zvVbkhlp+z/QDg6zlBHeMJlkNJyDGLaIfpa0muDuCnOhL76HbCXwoikA5OQmkKpWJpNqXdm3AvhjJEuRnNV52toz7MlCY6R8HmK552AlNaDVSN/Vsb9bXVR430an/zO8QtoPb2K5IVRuDv+eTmxc2ut9jdBVOJnHwxkAh/VZjUatvJbHWOWyp1sa880miXLQP9TQGx4o751lTQlPaoDigu2MgcTWc0LhW3hmcf1mIdQ7n250W42dJEBiT6nNfrZNLZ+xzHqY3nDX+lkki46lUNh7R7a8FPVj3aqJcpUBsFHQOyY5RKP6JnHhZ5yBuy3XpoIXlcsaVo5NhQY6A/CHisvFs0rbrXiNwStJxk5gT2VR4UKxn/lg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: acr-secret
    type: kubernetes.io/dockerconfigjson
